theme: jekyll-theme-dinky
title: "Spring 2018<br>CS 839<br>Data Science"
description: 
  "Wen-Fu Lee
  <br>
  <font size="6">(wlee256@wisc.edu)</font>
  <br>
  Yuan-Ting Hsieh
  <br>
  <font size="6">(yhsieh28@wisc.edu)</font>
  <br>
  Yahn-Chung Chen
  <br>
  <font size="6">(chen666@wisc.edu)</font>"
