theme: jekyll-theme-dinky
title: "Spring 2018<br><br>CS 839<br>Data Science"
description: 
  "Wen-Fu Lee<br>(wlee256@wisc.edu)<br>Yuan-Ting Hsieh<br>(yhsieh28@wisc.edu)<br>Yahn-Chung Chen<br>(chen666@wisc.edu)"
